name: Website Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '30 19 * * *' # every night at 01:00 AM IST

jobs:
  run-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install System Browsers
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y google-chrome-stable firefox
          
          # Edge
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
          sudo rm microsoft.gpg
          
          # Brave
          sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
          
          # Opera
          wget -qO- https://deb.opera.com/archive.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/opera.gpg > /dev/null
          echo deb [arch=amd64 signed-by=/usr/share/keyrings/opera.gpg] https://deb.opera.com/opera-stable/ stable non-free | sudo tee /etc/apt/sources.list.d/opera.list
          
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y microsoft-edge-stable brave-browser opera-stable

      - name: Install SeleniumBase drivers
        run: |
          sbase install chromedriver
          sbase install edgedriver
          sbase install geckodriver

      - name: Run Website Automation
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          MONGO_URI_ATLAS: ${{ secrets.MONGO_URI_ATLAS }}
        run: python main.py

      - name: Upload run report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: website-report
          path: logs/
          retention-days: 30
